// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package user

import (
	"database/sql"
)

type User struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	LineID    string       `json:"line_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}
