CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "line_id" varchar(100) UNIQUE NOT NULL,
  "created_at" timestamp DEFAULT (now())
);


-- name: CreateUser :one
INSERT INTO users(
  name, line_id
 ) VALUES (
  $1, $2
 )
 RETURNING *;

 -- name: GetUser :one
 SELECT id, name
 FROM users
 WHERE line_id = $1;

 -- name: DeleteUser :exec
 DELETE FROM users
 WHERE id = $1;