// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package store

import (
	"database/sql"
	"time"
)

type Shorturl struct {
	ID        int32        `json:"id"`
	UserID    int32        `json:"user_id"`
	Origin    string       `json:"origin"`
	Match     string       `json:"match"`
	ExpiredAt time.Time    `json:"expired_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type User struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	LineID    string       `json:"line_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}
