// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package shorturl

import (
	"context"
)

type Querier interface {
	CountMatchShorturl(ctx context.Context, match string) (int64, error)
	CreateShorturl(ctx context.Context, arg CreateShorturlParams) (Shorturl, error)
	DeleteShorturl(ctx context.Context, arg DeleteShorturlParams) error
	GetMatchShorturl(ctx context.Context, match string) (string, error)
	ListUserShorturl(ctx context.Context, userID int32) ([]ListUserShorturlRow, error)
	UpdateExpired(ctx context.Context, arg UpdateExpiredParams) (Shorturl, error)
}

var _ Querier = (*Queries)(nil)
